package config

import (
	"fmt"
	"strings"
)

func writePSD1File(path string, cfg Config) error {
	return writeWithBackupMode(path, []byte(renderPSD1(cfg)), 0o600)
}

func renderPSD1(cfg Config) string {
	var builder strings.Builder
	builder.WriteString("# ============================================\n")
	builder.WriteString("# Splunk Ping Monitor Configuration (Go v5)\n")
	builder.WriteString("# Generated by the embedded admin UI.\n")
	builder.WriteString("# ============================================\n\n")
	builder.WriteString("@{\n")
	fmt.Fprintf(&builder, "    config_schema_version = %d\n\n", cfg.ConfigSchemaVersion)
	fmt.Fprintf(&builder, "    pings_per_cycle = %d\n", cfg.PingsPerCycle)
	fmt.Fprintf(&builder, "    cycle_interval_seconds = %d\n", cfg.CycleIntervalSeconds)
	fmt.Fprintf(&builder, "    timeout_ms = %d\n", cfg.TimeoutMs)
	fmt.Fprintf(&builder, "    parallel_threads = %d\n\n", cfg.ParallelThreads)
	fmt.Fprintf(&builder, "    emit_individual_pings = %s\n\n", psd1Bool(cfg.EmitIndividualPings))
	fmt.Fprintf(&builder, "    output_mode = %s\n", psd1String(cfg.OutputMode))
	fmt.Fprintf(&builder, "    log_path = %s\n", psd1String(cfg.LogPath))
	fmt.Fprintf(&builder, "    log_rotation_size_mb = %d\n", cfg.LogRotationSizeMB)
	fmt.Fprintf(&builder, "    log_retention_files = %d\n", cfg.LogRetentionFiles)
	fmt.Fprintf(&builder, "    log_retention_days = %d\n", cfg.LogRetentionDays)
	fmt.Fprintf(&builder, "    log_compress_rotated = %s\n\n", psd1Bool(cfg.LogCompressRotated))

	builder.WriteString("    ping = @{\n")
	fmt.Fprintf(&builder, "        mode = %s\n", psd1String(cfg.Ping.Mode))
	builder.WriteString("    }\n\n")
	builder.WriteString("    health = @{\n")
	fmt.Fprintf(&builder, "        down_after_failures = %d\n", cfg.Health.DownAfterFailures)
	fmt.Fprintf(&builder, "        recovery_after_successes = %d\n", cfg.Health.RecoveryAfterSuccesses)
	fmt.Fprintf(&builder, "        stale_after_intervals = %d\n", cfg.Health.StaleAfterIntervals)
	builder.WriteString("    }\n\n")

	builder.WriteString("    diagnostics = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.Diagnostics.Enabled))
	fmt.Fprintf(&builder, "        handle_probe_mode = %s\n", psd1String(cfg.Diagnostics.HandleProbeMode))
	builder.WriteString("    }\n\n")

	builder.WriteString("    debug = @{\n")
	fmt.Fprintf(&builder, "        emit_memory_stats = %s\n", psd1Bool(cfg.Debug.EmitMemoryStats))
	builder.WriteString("    }\n\n")

	builder.WriteString("    hec = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.HEC.Enabled))
	fmt.Fprintf(&builder, "        url = %s\n", psd1String(cfg.HEC.URL))
	fmt.Fprintf(&builder, "        token = %s\n", psd1String(cfg.HEC.Token))
	fmt.Fprintf(&builder, "        index = %s\n", psd1String(cfg.HEC.Index))
	fmt.Fprintf(&builder, "        sourcetype = %s\n", psd1String(cfg.HEC.SourceType))
	fmt.Fprintf(&builder, "        verify_ssl = %s\n", psd1Bool(cfg.HEC.VerifySSL))
	fmt.Fprintf(&builder, "        ssl_protocol = %s\n\n", psd1String(cfg.HEC.SSLProtocol))
	fmt.Fprintf(&builder, "        batch_size = %d\n", cfg.HEC.BatchSize)
	fmt.Fprintf(&builder, "        drop_on_failure = %s\n", psd1Bool(cfg.HEC.DropOnFailure))
	fmt.Fprintf(&builder, "        max_buffer_events = %d\n", cfg.HEC.MaxBufferEvents)
	fmt.Fprintf(&builder, "        max_buffer_bytes = %s\n\n", psd1String(cfg.HEC.MaxBufferBytes))
	builder.WriteString("        retry = @{\n")
	fmt.Fprintf(&builder, "            enabled = %s\n", psd1Bool(cfg.HEC.Retry.Enabled))
	fmt.Fprintf(&builder, "            max_attempts = %d\n", cfg.HEC.Retry.MaxAttempts)
	fmt.Fprintf(&builder, "            base_delay_ms = %d\n", cfg.HEC.Retry.BaseDelayMs)
	fmt.Fprintf(&builder, "            jitter_pct = %d\n", cfg.HEC.Retry.JitterPct)
	fmt.Fprintf(&builder, "            backoff = %s\n", psd1String(cfg.HEC.Retry.Backoff))
	builder.WriteString("        }\n\n")
	fmt.Fprintf(&builder, "        retry_count = %d\n", cfg.HEC.RetryCount)
	fmt.Fprintf(&builder, "        retry_delay_ms = %d\n", cfg.HEC.RetryDelayMs)
	fmt.Fprintf(&builder, "        dead_letter_path = %s\n", psd1String(cfg.HEC.DeadLetterPath))
	fmt.Fprintf(&builder, "        dead_letter_rotation_size_mb = %d\n", cfg.HEC.DeadLetterRotationSizeMB)
	fmt.Fprintf(&builder, "        use_ack = %s\n", psd1Bool(cfg.HEC.UseACK))
	fmt.Fprintf(&builder, "        ack_timeout_seconds = %d\n", cfg.HEC.ACKTimeoutSeconds)
	fmt.Fprintf(&builder, "        ack_poll_interval_ms = %d\n", cfg.HEC.ACKPollIntervalMs)
	fmt.Fprintf(&builder, "        channel = %s\n", psd1String(cfg.HEC.Channel))
	builder.WriteString("    }\n\n")

	builder.WriteString("    metrics = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.Metrics.Enabled))
	fmt.Fprintf(&builder, "        mode = %s\n", psd1String(cfg.Metrics.Mode))
	fmt.Fprintf(&builder, "        index = %s\n", psd1String(cfg.Metrics.Index))
	fmt.Fprintf(&builder, "        hec_url = %s\n", psd1String(cfg.Metrics.HECURL))
	fmt.Fprintf(&builder, "        token = %s\n", psd1String(cfg.Metrics.Token))
	fmt.Fprintf(&builder, "        verify_ssl = %s\n", psd1Bool(cfg.Metrics.VerifySSL))
	fmt.Fprintf(&builder, "        ssl_protocol = %s\n\n", psd1String(cfg.Metrics.SSLProtocol))
	fmt.Fprintf(&builder, "        compat_mode = %s\n", psd1Bool(cfg.Metrics.CompatMode))
	fmt.Fprintf(&builder, "        sourcetype = %s\n", psd1String(cfg.Metrics.SourceType))
	fmt.Fprintf(&builder, "        event_name = %s\n", psd1String(cfg.Metrics.EventName))
	fmt.Fprintf(&builder, "        use_metrics_index = %s\n\n", psd1Bool(cfg.Metrics.UseMetricsIndex))
	fmt.Fprintf(&builder, "        batch_size = %d\n", cfg.Metrics.BatchSize)
	fmt.Fprintf(&builder, "        max_buffer_events = %d\n", cfg.Metrics.MaxBufferEvents)
	fmt.Fprintf(&builder, "        max_buffer_bytes = %s\n", psd1String(cfg.Metrics.MaxBufferBytes))
	fmt.Fprintf(&builder, "        use_ack = %s\n", psd1Bool(cfg.Metrics.UseACK))
	fmt.Fprintf(&builder, "        ack_timeout_seconds = %d\n", cfg.Metrics.ACKTimeoutSeconds)
	fmt.Fprintf(&builder, "        ack_poll_interval_ms = %d\n", cfg.Metrics.ACKPollIntervalMs)
	fmt.Fprintf(&builder, "        channel = %s\n", psd1String(cfg.Metrics.Channel))
	builder.WriteString("    }\n\n")

	builder.WriteString("    delivery = @{\n")
	fmt.Fprintf(&builder, "        spool_path = %s\n", psd1String(cfg.Delivery.SpoolPath))
	fmt.Fprintf(&builder, "        max_spool_bytes = %s\n", psd1String(cfg.Delivery.MaxSpoolBytes))
	fmt.Fprintf(&builder, "        max_envelopes = %d\n", cfg.Delivery.MaxEnvelopes)
	fmt.Fprintf(&builder, "        drain_max_envelopes = %d\n", cfg.Delivery.DrainMaxEnvelopes)
	builder.WriteString("    }\n\n")

	builder.WriteString("    discovery = @{\n")
	fmt.Fprintf(&builder, "        history_path = %s\n", psd1String(cfg.Discovery.HistoryPath))
	builder.WriteString("        schedules = @(\n")
	for _, schedule := range cfg.Discovery.Schedules {
		builder.WriteString("            @{\n")
		fmt.Fprintf(&builder, "                id = %s\n", psd1String(schedule.ID))
		fmt.Fprintf(&builder, "                enabled = %s\n", psd1Bool(schedule.Enabled))
		fmt.Fprintf(&builder, "                targets = %s\n", psd1StringArray(schedule.Targets))
		fmt.Fprintf(&builder, "                frequency = %s\n", psd1String(schedule.Frequency))
		fmt.Fprintf(&builder, "                day = %s\n", psd1String(schedule.Day))
		fmt.Fprintf(&builder, "                time = %s\n", psd1String(schedule.Time))
		fmt.Fprintf(&builder, "                timezone = %s\n", psd1String(schedule.Timezone))
		fmt.Fprintf(&builder, "                timeout_ms = %d\n", schedule.TimeoutMs)
		fmt.Fprintf(&builder, "                concurrency = %d\n", schedule.Concurrency)
		fmt.Fprintf(&builder, "                import_policy = %s\n", psd1String(schedule.ImportPolicy))
		builder.WriteString("            }\n")
	}
	builder.WriteString("        )\n")
	builder.WriteString("    }\n")
	builder.WriteString("}\n")
	return builder.String()
}

func psd1String(value string) string {
	return fmt.Sprintf("'%s'", strings.ReplaceAll(value, "'", "''"))
}

func psd1Bool(value bool) string {
	if value {
		return "$true"
	}
	return "$false"
}

func psd1StringArray(values []string) string {
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		encoded = append(encoded, psd1String(value))
	}
	return "@(" + strings.Join(encoded, ", ") + ")"
}
