package config

import (
	"fmt"
	"strings"
)

func writePSD1File(path string, cfg Config) error {
	return writeWithBackup(path, []byte(renderPSD1(cfg)))
}

func renderPSD1(cfg Config) string {
	var builder strings.Builder
	builder.WriteString("# ============================================\n")
	builder.WriteString("# Splunk Ping Monitor Configuration (Go v5)\n")
	builder.WriteString("# Generated by the embedded admin UI.\n")
	builder.WriteString("# ============================================\n\n")
	builder.WriteString("@{\n")
	fmt.Fprintf(&builder, "    pings_per_cycle = %d\n", cfg.PingsPerCycle)
	fmt.Fprintf(&builder, "    cycle_interval_seconds = %d\n", cfg.CycleIntervalSeconds)
	fmt.Fprintf(&builder, "    timeout_ms = %d\n", cfg.TimeoutMs)
	fmt.Fprintf(&builder, "    parallel_threads = %d\n\n", cfg.ParallelThreads)
	fmt.Fprintf(&builder, "    emit_individual_pings = %s\n\n", psd1Bool(cfg.EmitIndividualPings))
	fmt.Fprintf(&builder, "    output_mode = %s\n", psd1String(cfg.OutputMode))
	fmt.Fprintf(&builder, "    log_path = %s\n", psd1String(cfg.LogPath))
	fmt.Fprintf(&builder, "    log_rotation_size_mb = %d\n\n", cfg.LogRotationSizeMB)

	builder.WriteString("    ping = @{\n")
	fmt.Fprintf(&builder, "        mode = %s\n", psd1String(cfg.Ping.Mode))
	builder.WriteString("    }\n\n")

	builder.WriteString("    diagnostics = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.Diagnostics.Enabled))
	fmt.Fprintf(&builder, "        handle_probe_mode = %s\n", psd1String(cfg.Diagnostics.HandleProbeMode))
	builder.WriteString("    }\n\n")

	builder.WriteString("    debug = @{\n")
	fmt.Fprintf(&builder, "        emit_memory_stats = %s\n", psd1Bool(cfg.Debug.EmitMemoryStats))
	builder.WriteString("    }\n\n")

	builder.WriteString("    hec = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.HEC.Enabled))
	fmt.Fprintf(&builder, "        url = %s\n", psd1String(cfg.HEC.URL))
	fmt.Fprintf(&builder, "        token = %s\n", psd1String(cfg.HEC.Token))
	fmt.Fprintf(&builder, "        index = %s\n", psd1String(cfg.HEC.Index))
	fmt.Fprintf(&builder, "        sourcetype = %s\n", psd1String(cfg.HEC.SourceType))
	fmt.Fprintf(&builder, "        verify_ssl = %s\n", psd1Bool(cfg.HEC.VerifySSL))
	fmt.Fprintf(&builder, "        ssl_protocol = %s\n\n", psd1String(cfg.HEC.SSLProtocol))
	fmt.Fprintf(&builder, "        batch_size = %d\n", cfg.HEC.BatchSize)
	fmt.Fprintf(&builder, "        drop_on_failure = %s\n", psd1Bool(cfg.HEC.DropOnFailure))
	fmt.Fprintf(&builder, "        max_buffer_events = %d\n", cfg.HEC.MaxBufferEvents)
	fmt.Fprintf(&builder, "        max_buffer_bytes = %s\n\n", psd1String(cfg.HEC.MaxBufferBytes))
	builder.WriteString("        retry = @{\n")
	fmt.Fprintf(&builder, "            enabled = %s\n", psd1Bool(cfg.HEC.Retry.Enabled))
	fmt.Fprintf(&builder, "            max_attempts = %d\n", cfg.HEC.Retry.MaxAttempts)
	fmt.Fprintf(&builder, "            base_delay_ms = %d\n", cfg.HEC.Retry.BaseDelayMs)
	fmt.Fprintf(&builder, "            jitter_pct = %d\n", cfg.HEC.Retry.JitterPct)
	fmt.Fprintf(&builder, "            backoff = %s\n", psd1String(cfg.HEC.Retry.Backoff))
	builder.WriteString("        }\n\n")
	fmt.Fprintf(&builder, "        retry_count = %d\n", cfg.HEC.RetryCount)
	fmt.Fprintf(&builder, "        retry_delay_ms = %d\n", cfg.HEC.RetryDelayMs)
	fmt.Fprintf(&builder, "        dead_letter_path = %s\n", psd1String(cfg.HEC.DeadLetterPath))
	fmt.Fprintf(&builder, "        dead_letter_rotation_size_mb = %d\n", cfg.HEC.DeadLetterRotationSizeMB)
	builder.WriteString("    }\n\n")

	builder.WriteString("    metrics = @{\n")
	fmt.Fprintf(&builder, "        enabled = %s\n", psd1Bool(cfg.Metrics.Enabled))
	fmt.Fprintf(&builder, "        mode = %s\n", psd1String(cfg.Metrics.Mode))
	fmt.Fprintf(&builder, "        index = %s\n", psd1String(cfg.Metrics.Index))
	fmt.Fprintf(&builder, "        hec_url = %s\n", psd1String(cfg.Metrics.HECURL))
	fmt.Fprintf(&builder, "        token = %s\n", psd1String(cfg.Metrics.Token))
	fmt.Fprintf(&builder, "        verify_ssl = %s\n", psd1Bool(cfg.Metrics.VerifySSL))
	fmt.Fprintf(&builder, "        ssl_protocol = %s\n\n", psd1String(cfg.Metrics.SSLProtocol))
	fmt.Fprintf(&builder, "        compat_mode = %s\n", psd1Bool(cfg.Metrics.CompatMode))
	fmt.Fprintf(&builder, "        sourcetype = %s\n", psd1String(cfg.Metrics.SourceType))
	fmt.Fprintf(&builder, "        event_name = %s\n", psd1String(cfg.Metrics.EventName))
	fmt.Fprintf(&builder, "        use_metrics_index = %s\n\n", psd1Bool(cfg.Metrics.UseMetricsIndex))
	fmt.Fprintf(&builder, "        batch_size = %d\n", cfg.Metrics.BatchSize)
	fmt.Fprintf(&builder, "        max_buffer_events = %d\n", cfg.Metrics.MaxBufferEvents)
	fmt.Fprintf(&builder, "        max_buffer_bytes = %s\n", psd1String(cfg.Metrics.MaxBufferBytes))
	builder.WriteString("    }\n")
	builder.WriteString("}\n")
	return builder.String()
}

func psd1String(value string) string {
	return fmt.Sprintf("'%s'", strings.ReplaceAll(value, "'", "''"))
}

func psd1Bool(value bool) string {
	if value {
		return "$true"
	}
	return "$false"
}