# Ping Monitor Lookup Definitions

[ping_monitor_settings_lookup]
collection = ping_monitor_settings
external_type = kvstore
fields_list = _key, index, sourcetype, metrics_index, configured

[ping_health_lookup]
collection = ping_health_lookup
external_type = kvstore
fields_list = hostname, target_ip, group, entitytype, packet_loss_pct, avg_latency_ms, health_status, last_updated
