# Ping Monitor Lookup Definitions

[ping_monitor_settings_lookup]
collection = ping_monitor_settings
external_type = kvstore
fields_list = _key, index, sourcetype, metrics_index, configured

[ping_health_lookup]
filename = ping_health_lookup.csv
case_sensitive_match = false
